#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Umbrella\Console\Command\Doctrine as Doctrine;

require_once 'app/config/bootstrap.php';

$em = $app->getEm();
$helperSet = ConsoleRunner::createHelperSet($em);

$application = new Application('Bella Console Application', '1.0');
$application->setHelperSet($helperSet);

$application->addCommands(array(
    new Doctrine\Schema\CreateSchemaCommand(),
    new Doctrine\Schema\DropSchemaCommand(),
    new Doctrine\Schema\UpdateSchemaCommand(),
    new Doctrine\GenerateEntitiesCommand()
));
$application->run();