#    route_name:
#        path: /path
#        controller: HomeController:index 
#    maybe replace `:` with `@` and get the action on the same line as controller

default_route:
    path: /
    controller: IndexController
    action: indexAction

test_route:
    path: /test
    controller: TestController
    action: indexAction

hello_route:
    path: /hello/{name} # Does not work yet...
    controller: HelloController
    action: helloAction
