#    route_name:
#        path: /path
#        controller: HomeController@index 
#
# add ability to place directories in front of controllers. e.g. Blog:ShowController@showAction
# or There:Is:No:Limit:To:The:Number:Of:Parent:Directories:SomeController@someAction

default_route:
    path: /
    controller: IndexController@indexAction

test_route:
    path: /test
    controller: TestController@indexAction

hello_route:
    path: /hello
    controller: HelloController@helloAction
