#    route_name:
#        path: /path
#        controller: HomeController@index 

welcome_route:
    path: /
    controller: WelcomeController@indexAction

test_route:
    path: /test
    controller: TestController@indexAction

hello_route:
    path: /hello/{name}
    controller: Testing:Parent:Directories:HelloController@helloAction
