#    route_name:
#        path: /path
#        controller: HomeController@index 

default_route:
    path: /
    controller: IndexController@indexAction

test_route:
    path: /test
    controller: TestController@indexAction

hello_route:
    path: /hello
    controller: Testing:Parent:Directories:HelloController@helloAction
